# A simple UKF + CSS simulation

In this notebook:
* A 3U CubeSat with 6 Coarse Sun Sensor (CSS) rotating in with constant angular velocity around local and global coordinate systems
* A Simulator to model the state-variables (position, attitude, velocity, and angular velocity) and sensor-observation (light intensity)

_Here we use Homogeneous Coordinates and Unit Quaternions_

In [1]:
%matplotlib inline

import numpy as np
import transforms3d as tf
from math import pi as PI
from src.unscented_kalman_filter import UKF

import matplotlib.pyplot as plt
import seaborn as sns 

from ipywidgets import interact, interactive, IntSlider, FloatSlider, fixed

## Helpers

In [2]:
def h(sensors, light_source):
    '''
    Inputs:
    - sensors: A numpy array of shape [num_sensors, 3]
    - light_source: A numpy array of shape [3]
    '''
    def f(state):
        '''
        Inputs:
        - state: position (3), attitude (4), velocity (3), and angular-velocity (4)        
        '''
        
        # map light_source's position from Homogeneous Coordinates to Cartesian Coordinate
        p = light_source[:-1] / light_source[-1]
        # a unit vector pointing to the light_source in local coordinates
        u = p - state[:3]
        u = u / np.linalg.norm(u)
        # quaternion to rotation matrix
        r = tf.quaternions.quat2mat(state[3:7])
        # normal vector of sensors in local coordinates
        n = np.dot(sensors, r.T)
        # dot product between the normal vector to sensor and unit vector to the light_source
        d = np.dot(n, u)
        # reshold
        d[d < 0] = 0
        
        return d
    
    return f

In [3]:
class Observation:
    def __init__(self, sensors, light_source, std, h):
        '''
        Inputs:
        - sensors: A numpy array of shape [num_sensors, 3]
        - light_source: A numpy array of shape [3]
        - std: indicates the error in the sensor observation
        - h: a function that maps from state-space to observation-space
        '''
        self.h = h(sensors, light_source)
        self.std = std
        
    def measure(self, state):
        z = self.h(state)
        return z + np.random.randn(*z.shape) * self.std

In [4]:
class Simulator:
    def __init__(self, x0, w_std, obs):
        '''
        Inputs:
        - x0: initial state, [position (3), attitude (4), velocity (3), and angular-velocity (4)]
        - w_std: indicates the error in the angular velocity
        - obs: observation model
        '''
        self.X = x0
        self.w_std = w_std
        self.obs = obs
    def step(self):
        pred = tf.quaternions.qmult(self.X[3:7], self.X[-4:])
        err = self.X[3:7] = tf.quaternions.axangle2quat(
            [np.random.randn() for _ in xrange(3)],
            PI * np.random.randn() * self.w_std
        )
        self.X[3:7] = tf.quaternions.qmult(pred, err)
        return np.copy(self.X), self.obs.measure(self.X)
    def run(self, steps):
        S, Z = [], []
        for i_step in xrange(steps):
            _s, _z = self.step()
            S.append(_s)
            Z.append(_z)
            
        return np.array(S), np.array(Z)

## Test Models

In [5]:
tf.quaternions.axangle2quat([0,0,1], PI/18) # angular velocity

array([ 0.9961947 ,  0.        ,  0.        ,  0.08715574])

In [6]:
tf.quaternions.axangle2quat([1,1,1], 0) # angular orientation

array([ 1.,  0.,  0.,  0.])

In [7]:
light_source = np.array([0, 0, 0, 1])
x0 = np.array([
    10., 10., 10., # position
    1.,0.,0.,0., # angular orientation
    0.,0.,0., # velocity
    0.9961947,0.,0.,0.08715574 # angular velocity
])

sensors = np.array([
    [ 1, 0, 0], # +x
    [-1, 0, 0], # -x
    [0,  1, 0], # +y
    [0, -1, 0], # -y
    [0, 0,  1], # +z
    [0, 0, -1], # -z
])

w_std, obs_std = 1e-2, 1e-2

In [8]:
obs = Observation(sensors, light_source, obs_std, h)
sim = Simulator(x0, w_std, obs)
S, Z = sim.run(9)

In [9]:
tf.quaternions.quat2axangle(S[-1][3:7])

(array([-0.0375501 ,  0.04811692,  0.99813564]), 1.545258457199283)